# Generated by Django 6.0.5 on 2026-05-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(default='SIGIF', max_length=150)),
                ('nit', models.CharField(default='900.123.456-7', max_length=50)),
                ('direccion', models.CharField(default='CASA DE MOYA "LA AURORA" ', max_length=255)),
                ('moneda', models.CharField(default='COP ($) - Pesos Colombianos', max_length=50)),
                ('impuesto', models.CharField(default='19%', max_length=10)),
                ('correo_contacto', models.EmailField(default='soporte@sigif.com', max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='DatosEmpresa',
        ),
    ]
