# Generated by Django 6.0.5 on 2026-05-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_taller', models.CharField(max_length=150, verbose_name='Nombre del Taller / Empresa')),
                ('nit_o_rut', models.CharField(max_length=50, unique=True, verbose_name='NIT o Identificación')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono de Contacto')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=19.0, max_digits=5, verbose_name='Porcentaje de IVA / Impuesto')),
                ('moneda', models.CharField(default='COP ($)', max_length=10, verbose_name='Moneda del Sistema')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Datos de la Empresa',
                'verbose_name_plural': 'Datos de la Empresa',
            },
        ),
    ]
