# Generated by Django 5.2.10 on 2026-03-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contra', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=12)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(help_text='YYYY-MM-DD')),
                ('cargo', models.CharField(choices=[('Admin', 'ADMIN'), ('Empleado', 'EMPLEADO')], default='Empleado', max_length=15)),
            ],
        ),
    ]
