# Generated by Django 6.0.3 on 2026-04-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuarios_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
